// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBccnATAOGL_EfbqSASSZQpv552rhpGOZE',
    appId: '1:74341742529:web:0913aadbbbfbd57bac6140',
    messagingSenderId: '74341742529',
    projectId: 'kaihatsudojo-flutter',
    authDomain: 'kaihatsudojo-flutter.firebaseapp.com',
    storageBucket: 'kaihatsudojo-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX4NXRKz-6HDBWEMEN4RI3wdLSQve6gOE',
    appId: '1:74341742529:android:eef72e1a30d62b99ac6140',
    messagingSenderId: '74341742529',
    projectId: 'kaihatsudojo-flutter',
    storageBucket: 'kaihatsudojo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjAjDVDQUYHTW7kmRzAedjE0JStvq0mM',
    appId: '1:74341742529:ios:e6329eeca9eeca7dac6140',
    messagingSenderId: '74341742529',
    projectId: 'kaihatsudojo-flutter',
    storageBucket: 'kaihatsudojo-flutter.appspot.com',
    iosClientId: '74341742529-nl89qaigar8nskdbkmpbbkgmfmrldpbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbjAjDVDQUYHTW7kmRzAedjE0JStvq0mM',
    appId: '1:74341742529:ios:e6329eeca9eeca7dac6140',
    messagingSenderId: '74341742529',
    projectId: 'kaihatsudojo-flutter',
    storageBucket: 'kaihatsudojo-flutter.appspot.com',
    iosClientId: '74341742529-nl89qaigar8nskdbkmpbbkgmfmrldpbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
